### ISSUE TITLE
Upgrade Jackson dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j-tools#58]
Main RDF4J project uses 2.8.8, while tools still uses 2.8.2

**Comment by aschwarte10** [comment]
@barthanssens  I am planning to upgrade rdf4j main and rdf4j-storage to jackson 2.9.5 (see https://github.com/eclipse/rdf4j/issues/1035 and https://github.com/eclipse/rdf4j-storage/issues/75)

How about reusing this issue to also do this for the rdf4j-tools project? Is it ok if I amend your PR?

**Comment by barthanssens** [comment]
Sure, go ahead

**Comment by aschwarte10** [comment]
Change is now merged, CQ requests are tracked in https://github.com/eclipse/rdf4j/issues/1035

Closing this issue
